services:
  db:
    image: postgres:16
    container_name: PostgreSQL_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_SECRET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SECRET}
      POSTGRES_DB: ${DB_NAME_SECRET}
    ports:
      - "5432:5432"
    volumes:
      - ./script/create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql
      
      # תיקון המיפוי: אנחנו מצמידים את התיקייה מהמחשב לאותו שם בדיוק בדוקר
      # הוספת :z עוזרת לפתור בעיות הרשאה במערכות מסוימות
      - ./DataImportFiles:/DataImportFiles:z
      - ./MockarooFiles:/MockarooFiles:z
      
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminApp
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: