SET search_path TO public;

DROP TABLE IF EXISTS BOOKING_DETAILS;
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS GALLERY_IMAGES;
DROP TABLE IF EXISTS BOOKINGS;
DROP TABLE IF EXISTS ATTRACTIONS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS USERS;

DROP SCHEMA IF EXISTS public CASCADE;