SET search_path TO public;

SELECT * FROM USERS;
SELECT * FROM BOOKINGS;
SELECT * FROM CATEGORIES;
SELECT * FROM DIFFICULTY_LEVELS;
SELECT * FROM ATTRACTIONS;
SELECT * FROM GALLERY_IMAGES;
SELECT * FROM REVIEWS;
SELECT * FROM BOOKING_DETAILS;